services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezsystems.platformui.component.app:
        class: EzSystems\HybridPlatformUi\Components\App
        arguments:
            - "@templating"
            - "@ezsystems.platformui.component.maincontent"
            - "@ezsystems.platformui.component.navigationhub"
            - ["@ezsystems.platformui.component.discoverybar"]
        public: false

    ezsystems.platformui.component.navigationhub:
        class: EzSystems\HybridPlatformUi\Components\NavigationHub
        arguments:
            - "@templating"
            - '@=service("request_stack").getMasterRequest()'
            - []
            - []
        public: false

    ezsystems.platformui.component.maincontent:
        class: EzSystems\HybridPlatformUi\Components\MainContent
        arguments:
            - "@templating"
