services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezsystems.platformui.hybrid.mapper.pjax_response_to_main_content:
        class: EzSystems\HybridPlatformUi\Pjax\PjaxResponseMainContentMapper
        arguments:
            - "@ezsystems.platformui.component.app"

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMatcher: '@EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher'

    EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher: ~
