services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\HybridPlatformUi\EventSubscriber\PjaxSubscriber:
        arguments:
            $pjaxRequestMatcher: "@ezsystems.platformui.pjax.request_matcher"
        public: true

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMainContentMapper: '@EzSystems\HybridPlatformUi\Pjax\XpathPjaxResponseMainContentMapper'

    EzSystems\HybridPlatformUi\Pjax\XpathPjaxResponseMainContentMapper: ~
