services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMainContentMapper:
        alias: EzSystems\HybridPlatformUi\Pjax\DomXpathPjaxResponseMainContentMapper

    EzSystems\HybridPlatformUi\Pjax\DomXpathPjaxResponseMainContentMapper:
        arguments:
            - "@ezsystems.platformui.component.app"

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMatcher: '@EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher'

    EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher: ~
