services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\HybridPlatformUiBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    EzSystems\HybridPlatformUi\EventSubscriber\:
        resource: '../../../lib/EventSubscriber'
        public: true
        tags: ['kernel.event_subscriber']


    EzSystems\HybridPlatformUi\Http\AdminRequestMatcher:
        class: EzSystems\HybridPlatformUi\Http\AdminRequestMatcher\HardcodedAdminRequestMatcher
        calls:
            - [setExcludedRoutesPrefixes, ['%ezpublish.default_router.non_siteaccess_aware_routes%']]

    EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher:
        class: EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher\HeaderAjaxUpdateRequestMatcher

    EzSystems\HybridPlatformUi\App\AppResponseRenderer:
        class: EzSystems\HybridPlatformUi\App\RequestAppResponseRenderer
        arguments:
            $request: '@=service("request_stack").getMasterRequest()'

    EzSystems\HybridPlatformUi\EventSubscriber\ComponentRendererSubscriber:
        arguments:
            - "@ezsystems.platformui.pjax.request_matcher"

    EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher:
        class: EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher\AttributeHtmlFormatRequestMatcher

    EzSystems\HybridPlatformUi\Http\HybridRequestMatcher:
        class: EzSystems\HybridPlatformUi\Http\HybridRequestMatcher\ChainHybridRequestMatcher

    EzSystems\HybridPlatformUi\View\CoreViewMainContentMapper:
        class: EzSystems\HybridPlatformUi\View\AppConfigCoreViewMainContentMapper

    eZ\Publish\API\Repository\SearchService: "@ezpublish.api.service.search"
    eZ\Publish\API\Repository\LocationService: "@ezpublish.api.service.location"

    EzSystems\HybridPlatformUi\Filter\VersionFilter: ~

    EzSystems\HybridPlatformUi\Repository\PathService: ~

    EzSystems\HybridPlatformUi\Repository\DecoratedLocationService:
