services:
    ezsystems.platformui.hybrid.request_matcher.admin:
        class: EzSystems\HybridPlatformUi\Http\HardcodedAdminRequestMatcher

    ezsystems.platformui.hybrid.request_matcher.ajax_update:
        class: EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher

    ezsystems.platformui.hybrid.event_subscriber.app_renderer:
        class: EzSystems\HybridPlatformUi\EventSubscriber\AppRendererSubscriber
        arguments:
            - "@ezsystems.platformui.component.app"
            - "@ezsystems.platform_ui.hybrid.app.request_app_response_renderer"
            - "@ezsystems.hybrid_platform_ui.http.request_matcher.hybrid"
        tags:
            - {name: kernel.event_subscriber}

    ezsystems.platform_ui.hybrid.app.request_app_response_renderer:
        class: EzSystems\HybridPlatformUi\App\RequestAppResponseRenderer
        arguments:
            - '@=service("request_stack").getMasterRequest()'
            - '@ezsystems.platformui.hybrid.request_matcher.ajax_update'

    ezsystems.platformui.hybrid.event_subscriber.component_renderer:
        class: EzSystems\HybridPlatformUi\EventSubscriber\ComponentRendererSubscriber
        arguments:
            - "@ezsystems.platformui.pjax.request_matcher"
        tags:
            - {name: kernel.event_subscriber}

    ezsystems.hybrid_platform_ui.http.request_matcher.html_format:
        class: EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher

    ezsystems.hybrid_platform_ui.http.request_matcher.hybrid:
        class: EzSystems\HybridPlatformUi\Http\ChainRequestMatcher
        arguments:
            - "@ezsystems.platformui.hybrid.request_matcher.admin"
            - "@ezsystems.hybrid_platform_ui.http.request_matcher.html_format"
