services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [setContainer, ['@service_container']]

    EzSystems\HybridPlatformUiBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    ezsystems.platformui.hybrid.request_matcher.admin:
        class: EzSystems\HybridPlatformUi\Http\HardcodedAdminRequestMatcher
        calls:
            - [setExcludedRoutesPrefixes, ['%ezpublish.default_router.non_siteaccess_aware_routes%']]

    ezsystems.platformui.hybrid.request_matcher.ajax_update:
        class: EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher

    ezsystems.platformui.hybrid.event_subscriber.app_renderer:
        class: EzSystems\HybridPlatformUi\EventSubscriber\AppRendererSubscriber
        arguments:
            - "@ezsystems.platformui.component.app"
            - "@ezsystems.platform_ui.hybrid.app.request_app_response_renderer"
            - "@ezsystems.hybrid_platform_ui.http.request_matcher.hybrid"
        tags:
            - {name: kernel.event_subscriber}

    ezsystems.platform_ui.hybrid.app.request_app_response_renderer:
        class: EzSystems\HybridPlatformUi\App\RequestAppResponseRenderer
        arguments:
            - '@=service("request_stack").getMasterRequest()'
            - '@ezsystems.platformui.hybrid.request_matcher.ajax_update'

    ezsystems.platformui.hybrid.event_subscriber.component_renderer:
        class: EzSystems\HybridPlatformUi\EventSubscriber\ComponentRendererSubscriber
        arguments:
            - "@ezsystems.platformui.hybrid.request_matcher.admin"
        tags:
            - {name: kernel.event_subscriber}

    ezsystems.hybrid_platform_ui.http.request_matcher.html_format:
        class: EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher

    ezsystems.hybrid_platform_ui.http.request_matcher.hybrid:
        class: EzSystems\HybridPlatformUi\Http\ChainRequestMatcher
        arguments:
            - "@ezsystems.platformui.hybrid.request_matcher.admin"
            - "@ezsystems.hybrid_platform_ui.http.request_matcher.html_format"

    ezsystems.platformui.hybrid.event_subscriber.core_view:
        class: EzSystems\HybridPlatformUi\EventSubscriber\CoreViewSubscriber
        arguments:
            $adminRequestMatcher: "@ezsystems.platformui.hybrid.request_matcher.admin"
        tags:
            - {name: kernel.event_subscriber}

    EzSystems\HybridPlatformUi\View\CoreViewMainContentMapper: '@EzSystems\HybridPlatformUi\View\AppConfigCoreViewMainContentMapper'

    EzSystems\HybridPlatformUi\View\AppConfigCoreViewMainContentMapper:
        arguments:
            - "@ezsystems.platformui.component.app"

    EzSystems\HybridPlatformUi\Filter\VersionFilter: ~

    EzSystems\HybridPlatformUi\Repository\PathService:
        arguments:
            - "@ezpublish.api.service.search"

    EzSystems\HybridPlatformUi\Repository\UiLocationService:
        arguments:
            - "@ezpublish.api.service.location"

    EzSystems\HybridPlatformUi\Repository\UiFieldGroupService:
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.fields_groups.list"
