services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [setContainer, ['@service_container']]

    EzSystems\HybridPlatformUiBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    EzSystems\HybridPlatformUi\EventSubscriber\:
        resource: '../../../lib/EventSubscriber'
        public: true
        tags: ['kernel.event_subscriber']

    EzSystems\HybridPlatformUi\EventSubscriber\PjaxSubscriber:
        arguments:
            $responseMapper: "@ezsystems.platformui.hybrid.mapper.pjax_response_to_main_content"
            $pjaxRequestMatcher: "@ezsystems.platformui.pjax.request_matcher"

    EzSystems\HybridPlatformUi\Http\AdminRequestMatcher:
        alias: EzSystems\HybridPlatformUi\Http\HardcodedAdminRequestMatcher

    EzSystems\HybridPlatformUi\Http\HardcodedAdminRequestMatcher:
        calls:
            - [setExcludedRoutesPrefixes, ['%ezpublish.default_router.non_siteaccess_aware_routes%']]

    EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher: ~

    EzSystems\HybridPlatformUi\EventSubscriber\AppRendererSubscriber:
        arguments:
            $app: "@ezsystems.platformui.component.app"
            $appRenderer: '@EzSystems\HybridPlatformUi\App\RequestAppResponseRenderer'

    EzSystems\HybridPlatformUi\App\RequestAppResponseRenderer:
        arguments:
            - '@=service("request_stack").getMasterRequest()'
            - '@EzSystems\HybridPlatformUi\Http\AjaxUpdateRequestMatcher'

    EzSystems\HybridPlatformUi\EventSubscriber\ComponentRendererSubscriber:
        arguments:
            - "@ezsystems.platformui.hybrid.request_matcher.admin"

    EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher:
        alias: EzSystems\HybridPlatformUi\Http\FormatAttributeHtmlFormatRequestMatcher

    EzSystems\HybridPlatformUi\Http\FormatAttributeHtmlFormatRequestMatcher: ~

    EzSystems\HybridPlatformUi\Http\HybridRequestMatcher:
        alias: EzSystems\HybridPlatformUi\Http\ChainHybridRequestMatcher

    EzSystems\HybridPlatformUi\Http\ChainHybridRequestMatcher:
        arguments:
            - '@EzSystems\HybridPlatformUi\Http\AdminRequestMatcher'
            - '@EzSystems\HybridPlatformUi\Http\HtmlFormatRequestMatcher'

    EzSystems\HybridPlatformUi\EventSubscriber\CoreViewSubscriber: ~

    EzSystems\HybridPlatformUi\View\CoreViewMainContentMapper:
        alias: 'EzSystems\HybridPlatformUi\View\AppConfigCoreViewMainContentMapper'

    EzSystems\HybridPlatformUi\View\AppConfigCoreViewMainContentMapper:
        arguments:
            - "@ezsystems.platformui.component.app"

    EzSystems\HybridPlatformUi\Filter\VersionFilter: ~

    EzSystems\HybridPlatformUi\Repository\PathService:
        arguments:
            - "@ezpublish.api.service.search"

    EzSystems\HybridPlatformUi\Repository\UiLocationService:
        arguments:
            - "@ezpublish.api.service.location"

    EzSystems\HybridPlatformUi\Repository\UiFieldGroupService:
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.fields_groups.list"
